### ISSUE TITLE
Action once, Return to menu

### ISSUE THREAD

**Issue by TiddlyTweeter** [Marxsal/polly#1]
> Mark S. wrote:
> I would like to incorporate this branch going forward as quickly as possible, so developments 
> in polly will immediately carry over to the other major platforms.

One thing I need your help with is to understand how to add to your "while" Magic Loops "action once, return to menu".

If I can see one example of that I should be able to work out the rest.

I want to add "menu-once" to allow restore "once" to run and return to menu.

Also, more ambitiously "menu-parrot" to allow (only) a **full** Parrot Now (i.e. files not in downloads also get cloned to the secondary location).

I'd like, if possible, to do that soonish.

TT

**Comment by Marxsal** [comment]
Meta-meta note -- I thought gh would notify me by mail when new issues were posted. Apparently not. 

menu-once -- Let me look into this. Maybe we can kill two birds with one stone. Hmm ... bad choice of metaphors.

Re "full parrot now", you mean directly copying from wiki dir to parrot dir? Without looking at download dir?

**Comment by Marxsal** [comment]
I think the technique for the return-to-menu ability will be to put the menu evaluation code and the restore loop all inside of one big infinite loop that is controlled by the state of a master variable. Inside the evaluation code, that variable can be set on/off per requirements. All exit statements can be removed, since once you've broken out of the main loop you are also out of the program. It's a cleaner way to do things, since you always know where your exit point is. It will be a few hours I think before I can get to it.

**Comment by TiddlyTweeter** [comment]
> @Marxsal  Re` "full parrot now", you mean directly copying from wiki dir to parrot dir? Without looking at download dir?

Yes. And partly so you can copy over non-html files too.

**Comment by Marxsal** [comment]
Hi @TiddlyTweeter -- I just loaded up branch "core-enabled-with-menu-loop". It works (or seems to) with the "once" option. There are a few extra steps to allow the "parrot-menu" to work like you want. The main decide-if-download-happened loop needs to be skipped when $mode="parrot-menu", and the existing parrot code needs to be moved to a function and then invoked in it's own if $mode="parrot-menu" section. It shouldn't take long, but I'm afraid if I did it now I'd break something. So maybe tomorrow sometime. Thanks!

**Comment by TiddlyTweeter** [comment]
Thanks, that is very helpful! Just catching up on "menu-once" will take me a little time.

**Comment by TiddlyTweeter** [comment]
###  | O - Restore Once            |

Great. It does the job. I'm still hazy on how it works (that is my small brain :-) but I was able to set different timeouts for "once-menu" (3 secs to menu refresh) and "polly-once.bat" (-run = "once" to 15 secs to termination). 

Its excellent to run "once-menu" from menu. User can stay in one interface.

**Comment by Marxsal** [comment]
Ok. Single-pass parroting was a lot more involved than I thought. I just updated core-enabled-with-menu-loop. Please check it out and verify that I didn't seriously break anything. Then we can roll it all up into the master and proceed with other objectives. Thanks!

**Comment by TiddlyTweeter** [comment]
I'll get to it tomorrow. I posted an update via GG. You can ignore it. I'll
fold it in with this.

J.

**Comment by TiddlyTweeter** [comment]
The Parroting worked. Its great to have it. I will devise some tests to tax it, but basically it seems very useful. Tx!

**Comment by TiddlyTweeter** [comment]
On the more recent changes. Under a settings.ini that is all relative addresses, after "expansion" under RUN INFO I see ...

>   |   Downloads dir: C:\bag\z_pa\PortableApps\tw_polly\dev\test\P\PollyApp\..\Users\Polly\Downloads (used by Polly)
  |       Wikis dir: **_..\tw-wikidir_**
  |     Backups dir: C:\bag\z_pa\PortableApps\tw_polly\dev\test\P\PollyApp\..\Users\Polly\Downloads\tw_backups\wikis
  | Zip backups dir: C:\bag\z_pa\PortableApps\tw_polly\dev\test\P\PollyApp\..\Users\Polly\Downloads\tw_backups\zipped

"Wikis dir:" does not appear expanded. I'm not clear why--whether bug or logic. 

It still works (I guess because its not directly involved in restoration?) 

TT

**Comment by Marxsal** [comment]
Wikis dir isn't used yet, and might never be --- I was thinking instead of just one wiki directory we might have a wikis-dir section with multiple wiki dir's listed. We might need a rule like "the download directory can never be a wiki dir" in order to prevent serious looping problems. So anyway ... I might have skipped expanding the wikis dir setting.

**Comment by TiddlyTweeter** [comment]
The _multiple wikidirs listed_ -- the idea would be their contained wiki might be auto-loaded on startup? Yes?

**Comment by Marxsal** [comment]
> The _multiple wikidirs listed_ -- the idea would be their contained wiki might be auto-loaded on startup? Yes?

Yes, a supersized version of Tony's original suggestion. But we probably want to disallow the use of the downloads directory. For one thing, if it has all the downloaded copies  of a file, each of them would also be tracked.

I'm currently thinking that the directories would only be loaded on start-up, since scanning them every few minutes would undoubtedly lead to performance issues.

**Comment by Marxsal** [comment]
I think this issue can be closed now, right? The sub-issues can move into their own issue threads.

**Comment by TiddlyTweeter** [comment]
Yes. Close it.
